using System.Text;
using System.Text.RegularExpressions;
using DrakeAssetForge.Models;

namespace DrakeAssetForge.Services;

/// <summary>
/// Writes the dispatcher Asset Forge owns, and a customize stub per item only when that file is missing.
/// </summary>
public static class ArtItemHookWriter
{
    public static void Write(string projectDir, IReadOnlyList<OwnedItemDocument> items)
    {
        if (string.IsNullOrWhiteSpace(projectDir) || !Directory.Exists(projectDir))
            return;

        var ns = ReadNamespace(projectDir);
        var customizeDir = Path.Combine(projectDir, "Customize");
        Directory.CreateDirectory(customizeDir);

        var cases = new StringBuilder();
        foreach (var item in items.OrderBy(i => i.Id, StringComparer.OrdinalIgnoreCase))
        {
            var typeName = ToTypeName(item.Id);
            var stub = Path.Combine(customizeDir, typeName + ".cs");
            if (!File.Exists(stub))
                File.WriteAllText(stub, Stub(ns, typeName, item.Id));

            cases.AppendLine($"            case \"{Escape(item.Id)}\":");
            cases.AppendLine($"                {typeName}.Apply(item);");
            cases.AppendLine("                break;");
        }

        var hooks = $$"""
            using DrakeModsLibs.Art;

            namespace {{ns}};

            /// <summary>
            /// Regenerated by Drakes Asset Forge. Do not edit. Change the item in Customize\&lt;id&gt;Customize.cs.
            /// </summary>
            internal static class ArtItemHooks
            {
                internal static void Apply(ArtItemContext item)
                {
                    switch (item.Id)
                    {
            {{cases.ToString().TrimEnd()}}
                    }
                }
            }
            """;
        File.WriteAllText(Path.Combine(projectDir, "ArtItemHooks.g.cs"), hooks.Replace("\r\n", "\n").Replace("\n", Environment.NewLine));
    }

    private static string Stub(string ns, string typeName, string id) =>
        $$"""
        using DrakeModsLibs.Art;

        namespace {{ns}};

        /// <summary>
        /// Generated once for {{id}}. Asset Forge will not overwrite this file.
        /// The loader already applied the editor and BepInEx config. Assignments here win.
        /// </summary>
        internal static class {{typeName}}
        {
            internal static void Apply(ArtItemContext item)
            {
                // item.DisplayName = "{{Escape(id)}}";
                // item.Description = "Custom description."; // empty keeps the donor prefab description
                // item.Scale = 0.1f;
                // item.SetMaterials("iron");
                // item.RequirementItem = "Wood";
                // item.RequirementAmount = 1;
            }
        }
        """.Replace("\r\n", "\n").Replace("\n", Environment.NewLine);

    private static string ReadNamespace(string projectDir)
    {
        var csproj = Directory.EnumerateFiles(projectDir, "*.csproj").FirstOrDefault();
        if (csproj != null)
        {
            var match = Regex.Match(File.ReadAllText(csproj), "<RootNamespace>([^<]+)</RootNamespace>");
            if (match.Success && !string.IsNullOrWhiteSpace(match.Groups[1].Value))
                return match.Groups[1].Value.Trim();
        }

        return ToTypeName(Path.GetFileName(projectDir.TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar)));
    }

    private static string ToTypeName(string id)
    {
        var chars = id.Select(c => char.IsLetterOrDigit(c) ? c : '_').ToArray();
        var name = new string(chars).Trim('_');
        if (name.Length == 0)
            name = "Item";
        if (!char.IsLetter(name[0]))
            name = "Item_" + name;
        return name + "Customize";
    }

    private static string Escape(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
