using System.Text;
using System.Text.RegularExpressions;
using DrakesForge.Format;
using DrakesForge.Format.Json;

namespace DrakesForge.App.Services;

public sealed class CodeExportResult
{
    public required string Folder { get; init; }
    public List<string> Written { get; } = new();
    public List<string> Kept { get; } = new();
    public string? ProjectFile { get; init; }
}

/// <summary>
/// Turns a pack into C#: Forge compiled into the mod from source (no Forge Runtime dependency), the pack
/// beside the DLL, and a Customize\&lt;Item&gt;.cs hook per item. Like the old Asset Forge export, files are
/// either regenerated every time (Forge\, ForgeHooks.g.cs, Pack\, manifest.json) or written once and then
/// owned by you (csproj, plugin, Customize\*, README, environment.props).
/// </summary>
public static class CodeProjectWriter
{
    public static string DefaultFolder(PackProject pack) =>
        Path.Combine(Path.GetDirectoryName(PackProject.DefaultPacksDirectory)!, "Projects", PushTarget.Sanitize(pack.Manifest.Id));

    public static string? ForgeSourceFolder()
    {
        var dir = Path.Combine(AppContext.BaseDirectory, "forge-src");
        return Directory.Exists(dir) ? dir : null;
    }

    /// <param name="intoExisting">
    /// Add to an existing mod: only Forge\, ForgeHooks.g.cs, Customize\, Pack\ and FORGE.md (how to hook it up);
    /// no csproj or plugin class.
    /// </param>
    public static CodeExportResult Write(PackProject pack, string folder, bool intoExisting, PushTarget? deployTo, string? valheimPath)
    {
        var src = ForgeSourceFolder() ?? throw new DirectoryNotFoundException("This build of the app doesn't include the Forge source (forge-src).");
        Directory.CreateDirectory(folder);

        var name = PushTarget.Sanitize(pack.Manifest.Id);
        var ns = intoExisting ? ReadNamespace(folder) ?? name : name;
        var author = PushTarget.Sanitize(pack.Manifest.Author.Length > 0 ? pack.Manifest.Author : "Unknown");
        var result = new CodeExportResult { Folder = folder, ProjectFile = intoExisting ? null : Path.Combine(folder, name + ".csproj") };

        // Regenerated: Forge itself, namespaced into the mod so several mods can each embed their own copy.
        var forgeDir = Path.Combine(folder, "Forge");
        if (Directory.Exists(forgeDir))
            Directory.Delete(forgeDir, true);
        foreach (var file in Directory.GetFiles(src, "*.cs", SearchOption.AllDirectories))
        {
            var relative = Path.GetRelativePath(src, file);
            var code = File.ReadAllText(file)
                .Replace("DrakesForge.Format", ns + ".Forge.Format")
                .Replace("namespace DrakesForge.Runtime;", $"namespace {ns}.Forge;");
            Write(result, Path.Combine(forgeDir, relative),
                $"// <auto-generated>\n// Forge (Drakes Asset Forge) compiled into {name}. Regenerated on every export; don't edit.\n// </auto-generated>\n#nullable enable\n" + code);
        }

        // Regenerated: the pack, marked embedded so a shared Forge Runtime (if installed) doesn't load it twice.
        SyncPack(pack, Path.Combine(folder, "Pack"), result);

        // Customize\<Item>.cs: yours. Created once per item, never overwritten.
        var types = new Dictionary<string, string>();
        var used = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (var recipe in pack.Recipes.OrderBy(r => r.Id, StringComparer.OrdinalIgnoreCase))
        {
            var type = TypeName(recipe.Name ?? recipe.Id, used);
            types[recipe.Id] = type;
            WriteOnce(result, Path.Combine(folder, "Customize", type + ".cs"), CustomizeStub(ns, type, recipe));
        }

        var cases = new StringBuilder();
        foreach (var (id, type) in types)
            cases.Append($"\n            case \"{Escape(id)}\":\n                Customize.{type}.OnBuilt(item);\n                break;");
        Write(result, Path.Combine(folder, "ForgeHooks.g.cs"), $$"""
            // <auto-generated>
            // Regenerated by Drakes Asset Forge on every export. Put your code in Customize\<Item>.cs.
            // </auto-generated>
            #nullable enable
            using {{ns}}.Forge;

            namespace {{ns}};

            internal static class ForgeHooks
            {
                /// <summary>Called by Forge right after it builds each item from Pack\, and again after hot reloads.</summary>
                internal static void OnBuilt(ForgeBuiltContext item)
                {
                    switch (item.Id)
                    {{{cases}}
                    }
                }
            }
            """);

        if (intoExisting)
        {
            Write(result, Path.Combine(folder, "FORGE.md"), HookupGuide(ns, name));
        }
        else
        {
            WriteOnce(result, Path.Combine(folder, name + ".csproj"), Csproj(name, ns, author, pack.Manifest.Version, "Pack"));
            WriteOnce(result, Path.Combine(folder, name + "Plugin.cs"), Plugin(name, ns, author, pack.Manifest.Version));
            WriteOnce(result, Path.Combine(folder, "environment.props"), EnvironmentProps(valheimPath, deployTo));
            WriteOnce(result, Path.Combine(folder, ".gitignore"), "bin/\nobj/\nenvironment.props\n*.user\n");
            WriteOnce(result, Path.Combine(folder, "README.md"), ReadPackFile(pack, "README.md") ?? ThunderstoreFiles.DefaultReadme(pack));
            Write(result, Path.Combine(folder, "manifest.json"), ThunderstoreFiles.Manifest(pack, ThunderstoreFiles.CodeModDependencies));
            CopyIfExists(pack, "CHANGELOG.md", folder, result);
            CopyIfExists(pack, "icon.png", folder, result);
        }

        return result;
    }

    private static void SyncPack(PackProject pack, string dest, CodeExportResult result)
    {
        Directory.CreateDirectory(dest);
        var wanted = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (var file in pack.ShippedFiles())
        {
            var relative = Path.GetRelativePath(pack.Root, file);
            // Thunderstore files belong to the project root, not the embedded pack.
            if (relative is "README.md" or "CHANGELOG.md" or "icon.png" or "manifest.json")
                continue;
            wanted.Add(relative);
            var to = Path.Combine(dest, relative);
            Directory.CreateDirectory(Path.GetDirectoryName(to)!);
            if (relative == ForgePack.FileName)
            {
                var manifest = RecipeSerializer.ReadPack(File.ReadAllText(file), new List<string>());
                manifest.Embedded = true;
                File.WriteAllText(to, RecipeSerializer.WritePack(manifest));
            }
            else
            {
                File.Copy(file, to, true);
            }
        }

        foreach (var stale in Directory.GetFiles(dest, "*", SearchOption.AllDirectories))
            if (!wanted.Contains(Path.GetRelativePath(dest, stale)))
                File.Delete(stale);
        result.Written.Add(dest + Path.DirectorySeparatorChar);
    }

    private static string CustomizeStub(string ns, string type, ItemRecipe recipe)
    {
        var examples = recipe.Kind == RecipeKind.Piece
            ? new[] { "// var piece = item.Piece!;", "// piece.m_comfort = 2;", "// item.AddComponentOnce<MyPieceBehaviour>();" }
            : new[] { "// var shared = item.Shared!;", "// shared.m_maxDurability = 500;", "// shared.m_damages.m_fire = 10;", "// item.AddComponentOnce<MyItemBehaviour>();" };
        var exampleText = string.Join("\n        ", examples);
        return $$"""
            using {{ns}}.Forge;
            using UnityEngine;

            namespace {{ns}}.Customize;

            /// <summary>
            /// Your code for "{{Escape(recipe.Name ?? recipe.Id)}}" ({{recipe.Id}}: {{recipe.Kind.ToString().ToLowerInvariant()}} from {{recipe.Base}}).
            /// Runs right after Forge builds it from Pack\items, and again after every hot reload (the prefab is reset first).
            /// Drakes Asset Forge creates this file once and never overwrites it.
            /// </summary>
            internal static class {{type}}
            {
                internal static void OnBuilt(ForgeBuiltContext item)
                {
                    // item.Prefab is the built GameObject; the recipe's look, fields and recipe are already applied.
                    {{exampleText}}
                }
            }
            """;
    }

    private static string Plugin(string name, string ns, string author, string version) => $$"""
        using System.IO;
        using BepInEx;
        using {{ns}}.Forge;

        namespace {{ns}};

        /// <summary>
        /// {{name}}: items built by Forge (compiled into this mod) from Pack\, with your code in Customize\.
        /// Created once by Drakes Asset Forge; it's yours to change.
        /// </summary>
        [BepInPlugin(Guid, Name, Version)]
        [BepInDependency("com.jotunn.jotunn")]
        public sealed class {{name}}Plugin : BaseUnityPlugin
        {
            public const string Guid = "{{author.ToLowerInvariant()}}.{{name.ToLowerInvariant()}}";
            public const string Name = "{{name}}";
            public const string Version = "{{version}}";

            private void Awake()
            {
                var options = new ForgeOptions { OnBuilt = ForgeHooks.OnBuilt };
                options.PackFolders.Add(Path.Combine(Path.GetDirectoryName(Info.Location)!, "Pack"));
                ForgeHost.Start(this, options, Logger);
            }
        }
        """;

    internal static string Csproj(string name, string ns, string author, string version, string data = "Pack") => $$"""
        <Project Sdk="Microsoft.NET.Sdk">
          <!-- Created by Drakes Asset Forge. Forge\ (if any) and {{data}}\ are regenerated on export; everything else is yours. -->
          <PropertyGroup>
            <TargetFramework>net481</TargetFramework>
            <AssemblyName>{{name}}</AssemblyName>
            <RootNamespace>{{ns}}</RootNamespace>
            <Version>{{version}}</Version>
            <LangVersion>latest</LangVersion>
            <Nullable>enable</Nullable>
            <ImplicitUsings>disable</ImplicitUsings>
            <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
            <ThunderstoreAuthor>{{author}}</ThunderstoreAuthor>
          </PropertyGroup>

          <!-- Machine paths (ValheimPath, ProfilePath): environment.props, not committed. -->
          <Import Project="environment.props" Condition="Exists('environment.props')" />
          <PropertyGroup>
            <ManagedPath>$(ValheimPath)\valheim_Data\Managed</ManagedPath>
            <BepInExPath>$(ProfilePath)\BepInEx</BepInExPath>
            <ValheimAssembly>$(ManagedPath)\publicized_assemblies\assembly_valheim_publicized.dll</ValheimAssembly>
            <ValheimAssembly Condition="!Exists('$(ValheimAssembly)')">$(ManagedPath)\assembly_valheim.dll</ValheimAssembly>
          </PropertyGroup>

          <ItemGroup>
            <Reference Include="BepInEx" HintPath="$(BepInExPath)\core\BepInEx.dll" Private="false" />
            <Reference Include="Jotunn" HintPath="$(BepInExPath)\plugins\ValheimModding-Jotunn\Jotunn.dll" Private="false" />
            <Reference Include="assembly_valheim" HintPath="$(ValheimAssembly)" Private="false" />
            <Reference Include="UnityEngine" HintPath="$(ManagedPath)\UnityEngine.dll" Private="false" />
            <Reference Include="UnityEngine.CoreModule" HintPath="$(ManagedPath)\UnityEngine.CoreModule.dll" Private="false" />
            <Reference Include="UnityEngine.ImageConversionModule" HintPath="$(ManagedPath)\UnityEngine.ImageConversionModule.dll" Private="false" />
            <Reference Include="UnityEngine.AssetBundleModule" HintPath="$(ManagedPath)\UnityEngine.AssetBundleModule.dll" Private="false" />
            <Reference Include="UnityEngine.ParticleSystemModule" HintPath="$(ManagedPath)\UnityEngine.ParticleSystemModule.dll" Private="false" />
            <Reference Include="UnityEngine.PhysicsModule" HintPath="$(ManagedPath)\UnityEngine.PhysicsModule.dll" Private="false" />
            <!-- Unity 6 modules target netstandard 2.1; net481 only has the 2.0 facade. -->
            <Reference Include="netstandard" HintPath="$(ManagedPath)\netstandard.dll" Private="false" />
          </ItemGroup>

          <ItemGroup>
            <None Include="{{data}}\**\*" CopyToOutputDirectory="PreserveNewest" />
            <ThunderstoreFile Include="manifest.json" Condition="Exists('manifest.json')" />
            <ThunderstoreFile Include="README.md" Condition="Exists('README.md')" />
            <ThunderstoreFile Include="CHANGELOG.md" Condition="Exists('CHANGELOG.md')" />
            <ThunderstoreFile Include="icon.png" Condition="Exists('icon.png')" />
          </ItemGroup>

          <!-- Build installs into the test profile, laid out like a Thunderstore install (hot reload works). -->
          <Target Name="DeployToProfile" AfterTargets="Build" Condition="'$(ForgeDeploy)' != 'false' and '$(ProfilePath)' != '' and Exists('$(BepInExPath)\plugins')">
            <ItemGroup>
              <ForgePackFiles Include="$(TargetDir){{data}}\**\*" />
            </ItemGroup>
            <PropertyGroup>
              <DeployDir>$(BepInExPath)\plugins\$(ThunderstoreAuthor)-$(AssemblyName)</DeployDir>
            </PropertyGroup>
            <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(DeployDir)" SkipUnchangedFiles="true" />
            <Copy SourceFiles="@(ForgePackFiles)" DestinationFiles="@(ForgePackFiles->'$(DeployDir)\{{data}}\%(RecursiveDir)%(Filename)%(Extension)')" SkipUnchangedFiles="true" />
            <Message Importance="high" Text="Deployed $(AssemblyName) to $(DeployDir)" />
          </Target>

          <!-- Release builds also make the Thunderstore zip in bin\. -->
          <Target Name="ThunderstoreZip" AfterTargets="Build" Condition="'$(Configuration)' == 'Release'">
            <PropertyGroup>
              <StageDir>$(BaseIntermediateOutputPath)thunderstore\</StageDir>
              <ZipPath>$(MSBuildProjectDirectory)\bin\$(ThunderstoreAuthor)-$(AssemblyName)-$(Version).zip</ZipPath>
            </PropertyGroup>
            <ItemGroup>
              <StageFiles Include="$(TargetDir){{data}}\**\*" />
            </ItemGroup>
            <RemoveDir Directories="$(StageDir)" />
            <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(StageDir)" />
            <Copy SourceFiles="@(StageFiles)" DestinationFiles="@(StageFiles->'$(StageDir){{data}}\%(RecursiveDir)%(Filename)%(Extension)')" />
            <Copy SourceFiles="@(ThunderstoreFile)" DestinationFolder="$(StageDir)" />
            <ZipDirectory SourceDirectory="$(StageDir)" DestinationFile="$(ZipPath)" Overwrite="true" />
            <Message Importance="high" Text="Thunderstore zip: $(ZipPath)" />
          </Target>
        </Project>
        """;

    internal static string EnvironmentProps(string? valheimPath, PushTarget? deployTo)
    {
        var profile = deployTo is { IsDevFolder: false } t ? Path.GetFullPath(Path.Combine(t.Folder, "..", "..")) : "";
        return $"""
            <Project>
              <!-- This machine's paths. Not committed (see .gitignore). -->
              <PropertyGroup>
                <ValheimPath>{valheimPath ?? @"C:\Program Files (x86)\Steam\steamapps\common\Valheim"}</ValheimPath>
                <!-- Mod-manager profile with BepInEx + Jotunn: references come from here and builds deploy here. -->
                <ProfilePath>{profile}</ProfilePath>
              </PropertyGroup>
            </Project>
            """;
    }

    private static string HookupGuide(string ns, string name) => $$"""
        # Forge in this mod

        Drakes Asset Forge added: `Forge\` (regenerated), `ForgeHooks.g.cs` (regenerated), `Pack\` (regenerated),
        and `Customize\*.cs` (yours, created once).

        1. In your plugin's `Awake()`:

        ```csharp
        var options = new {{ns}}.Forge.ForgeOptions { OnBuilt = ForgeHooks.OnBuilt };
        options.PackFolders.Add(System.IO.Path.Combine(System.IO.Path.GetDirectoryName(Info.Location)!, "Pack"));
        {{ns}}.Forge.ForgeHost.Start(this, options, Logger);
        ```

        2. In your `.csproj`, ship the pack beside the DLL:

        ```xml
        <ItemGroup>
          <None Include="Pack\**\*" CopyToOutputDirectory="PreserveNewest" />
        </ItemGroup>
        ```

        3. References Forge needs (most mods have them): BepInEx, Jotunn, assembly_valheim (publicized),
           UnityEngine, UnityEngine.CoreModule, UnityEngine.ImageConversionModule, UnityEngine.AssetBundleModule,
           UnityEngine.ParticleSystemModule,
           and Valheim's `netstandard.dll` from valheim_Data\Managed.

        Ship the `Pack` folder next to `{{name}}`'s DLL. No Forge Runtime dependency is needed.
        """;

    internal static void Write(CodeExportResult result, string path, string text)
    {
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        File.WriteAllText(path, text.Replace("\r\n", "\n").Replace("\n", Environment.NewLine));
        result.Written.Add(path);
    }

    internal static void WriteOnce(CodeExportResult result, string path, string text)
    {
        if (File.Exists(path))
        {
            result.Kept.Add(path);
            return;
        }

        Write(result, path, text);
    }

    internal static void CopyIfExists(PackProject pack, string file, string folder, CodeExportResult result)
    {
        var from = Path.Combine(pack.Root, file);
        if (!File.Exists(from))
            return;
        File.Copy(from, Path.Combine(folder, file), true);
        result.Written.Add(Path.Combine(folder, file));
    }

    internal static string? ReadPackFile(PackProject pack, string file)
    {
        var path = Path.Combine(pack.Root, file);
        return File.Exists(path) ? File.ReadAllText(path) : null;
    }

    internal static string? ReadNamespace(string folder)
    {
        foreach (var file in Directory.EnumerateFiles(folder, "*.cs", SearchOption.TopDirectoryOnly))
            if (Regex.Match(File.ReadAllText(file), @"^\s*namespace\s+([A-Za-z_][\w.]*)", RegexOptions.Multiline) is { Success: true } m)
                return m.Groups[1].Value;
        return null;
    }

    /// <summary>"Cape Wolf Black" → CapeWolfBlack; unique within the export.</summary>
    internal static string TypeName(string text, HashSet<string> used)
    {
        var words = Regex.Split(text, "[^A-Za-z0-9]+").Where(w => w.Length > 0).Select(w => char.ToUpperInvariant(w[0]) + w[1..]);
        var name = string.Concat(words);
        if (name.Length == 0 || char.IsDigit(name[0]))
            name = "Item" + name;
        var unique = name;
        for (var i = 2; !used.Add(unique); i++)
            unique = name + i;
        return unique;
    }

    internal static string Escape(string s) => s.Replace("\\", "\\\\").Replace("\"", "\\\"");
}

/// <summary>Thunderstore metadata kept in the pack folder (README.md, CHANGELOG.md, icon.png) and the generated manifest.</summary>
public static class ThunderstoreFiles
{
    // Packs can use sprites, effects and component changes, which need Forge Runtime 0.2.
    public const string ForgeRuntimeDependency = "DrakeMods-DrakesForgeRuntime-0.2.1";
    public const string JotunnDependency = "ValheimModding-Jotunn-2.30.2";
    public static readonly string[] DataPackDependencies = { ForgeRuntimeDependency, JotunnDependency };
    public static readonly string[] CodeModDependencies = { JotunnDependency };

    public static string Manifest(PackProject pack, IEnumerable<string> dependencies)
    {
        var deps = JsonValue.NewArray();
        foreach (var d in dependencies)
            deps.Add(d);
        var description = pack.Manifest.Description.Length > 0 ? pack.Manifest.Description : pack.Manifest.Name;
        return JsonValue.NewObject()
            .Set("name", PushTarget.Sanitize(pack.Manifest.Id))
            .Set("version_number", pack.Manifest.Version)
            .Set("website_url", pack.Manifest.Website)
            .Set("description", description.Length > 250 ? description[..250] : description)
            .Set("dependencies", deps)
            .ToJson();
    }

    public static string DefaultReadme(PackProject pack)
    {
        var sb = new StringBuilder();
        sb.Append($"# {pack.Manifest.Name}\n\n");
        if (pack.Manifest.Description.Length > 0)
            sb.Append(pack.Manifest.Description).Append("\n\n");
        sb.Append("## Contents\n\n");
        foreach (var r in pack.Recipes.OrderBy(r => r.Kind).ThenBy(r => r.Name ?? r.Id))
        {
            var what = r.Kind switch { RecipeKind.Piece => "Build piece", RecipeKind.Item => "Item", _ => "Reskin" };
            var cost = r.Craft?.Requirements.Count > 0 ? " · " + string.Join(", ", r.Craft.Requirements.Select(q => $"{q.Item} ×{q.Amount}")) : "";
            sb.Append($"- **{r.Name ?? r.Id}** ({what}, based on `{r.Base}`){cost}\n");
        }

        sb.Append("\nMade with Drakes Asset Forge.\n");
        return sb.ToString();
    }
}
